name: LegalAI CI

on:
  push:
    branches:
      - main  # Rulează workflow-ul când dai push pe `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Rulează pe Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Clonează codul în runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Folosește Python 3.12

      - name: Install Java (necesar pentru LanguageTool)
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # Poți folosi și 'temurin' sau 'zulu'
          java-version: '11'  # Java 11, recomandat pentru LanguageTool

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalează toate dependențele

      - name: Run script
        run: python mount/src/legalai/app.py  # Rulează scriptul tău
